client:
  build: client
  links:
    - server:scserver

server:
  build: server
  volumes:
    - tmp/server:/repo:rw
  ports:
    - "11300"
    - "1500"
    - "9418"

editor:
  build: editor
  links:
    - server:scserver
  ports:
    - "8080:8080"


test1:
  build: client
  command: sh -c "while true; do ls -la /config/; sleep 10; done"
  links:
    - server:scserver

